/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Log API
 * OpenAPI spec version: 1.0.0
 */

export type WorkLogApiListParams = {
/**
 * YYYY-MM 形式 (例: 2025-07) 
 */
month: string;
};
