/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Log API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkLog } from './workLog';

export interface WorkLogAggregation {
  /** その月の合計労働時間 (時間単位) */
  total_h: number;
  /** その月の合計コミュニケーション時間 (時間単位) */
  comm_h: number;
  /** その月の合計作業時間 (時間単位) */
  work_h: number;
  /** 日ごとのワークログ一覧 */
  logs: WorkLog[];
}
