/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Log API
 * OpenAPI spec version: 1.0.0
 */
import type { Id } from './id';

export interface WorkLog {
  id: Id;
  /**
   * 日付 (YYYY-MM-DD 形式)
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  date: string;
  /** 当日の合計労働時間 (時間単位) */
  total_h: number;
  /** 当日のコミュニケーション時間 (時間単位) */
  comm_h: number;
  /** 当日のコーディングなどの作業時間 (時間単位) */
  work_h: number;
  /**
   * メモ
   * @maxLength 500
   */
  memo?: string;
}
